# Generated by Django 4.0.3 on 2022-05-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id_cinema', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image', verbose_name='Изображение')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('actors', models.CharField(max_length=500, verbose_name='Актеры')),
                ('duration', models.CharField(max_length=20, verbose_name='Время')),
                ('age_limit', models.CharField(max_length=5, verbose_name='Возрастное ограничение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_contact', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id_hall', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hall', models.CharField(max_length=100, verbose_name='Название зала')),
                ('amount_row', models.IntegerField(verbose_name='Количество рядов')),
                ('amount_place', models.IntegerField(verbose_name='Количество мест в ряду')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Кинозалы',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id_timetable', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('id_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cinema', verbose_name='Название фильиа')),
                ('id_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('place', models.IntegerField(verbose_name='Место')),
                ('id_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.timetable', verbose_name='Название фильма')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
            },
        ),
    ]
