# Generated by Django 4.0.3 on 2022-04-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Кинозал', 'verbose_name_plural': 'Кинозалы'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='id_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hall', verbose_name='Зал'),
        ),
    ]
